# Generated by Django 3.2.4 on 2021-09-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('msg', models.TextField()),
            ],
        ),
    ]
